hdf5:
  - 2
  - 1.14.6
libnetcdf:
  - 4.10.0
  - 4.9.3
mpi:
  - mpich    # [unix]
  - msmpi    # [win]
  - impi-devel  # [win]
zip_keys:
  - - hdf5
    - libnetcdf
mkl_devel:
  - 2024  # [win and mpi == "msmpi"]
  - 2026  # [win and mpi != "msmpi"]
